version: '3.7'
services:
  sample:
    container_name: dovico.dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './public:/app/public'
      - './src:/app/src'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
