react:
  title: react
  color: cyan
  icon: fc06

js:
  title: javascript
  color: yellow
  icon: e781

docker:
  title: docker
  color: blue
  icon: f308

python:
  title: python
  color: orange
  icon: e73c

django:
  title: django
  color: green
  icon: e73c

php:
  title: php
  color: magenta
  icon: f81e

pg:
  title: postgresql
  color: blue
  icon: f6b7

mysql:
  title: mysql
  color: yellow
  icon: f6b7

spring:
  title: spring
  color: green
  icon: e738

java:
  title: java
  color: red
  icon: e738

c++:
  title: c++
  color: yellow
  icon: e61d

mongo:
  title: mongodb
  color: green
  icon: f6b7

win:
  title: windows
  color: blue
  icon: e70f

linux:
  title: linux
  color: magenta
  icon: e712

git:
  title: git
  color: magenta
  icon: e702

html:
  title: html
  color: red
  icon: e736

css:
  title: css
  color: yellow
  icon: e74a

gimp:
  title: gimp
  color: orange
  icon: e22b

italian:
  title: 
    en: "italian: native"
    it: "italiano: madrelingua"
  color: red
  icon: f6e6

english:
  title:
    en: "english: C1"
    it: "inglese: C1"
  color: blue
  icon: f6e6